app/Http/routes.php
<?php

/*
|--------------------------------------------------------------------------
| Application Routes
|--------------------------------------------------------------------------
|
| Here is where you can register all of the routes for an application.
| It's a breeze. Simply tell Laravel the URIs it should respond to
| and give it the controller to call when that URI is requested.
|
*/

Route::get('home', function () {
    return view('index');
});

Route::get('/', ['as' => 'home', function()
{
    return view('index');
}]);

Route::controllers([
	'auth' => 'Auth\AuthController',
	'password' => 'Auth\PasswordController',
]);

Route::resource('comments', 'CommentsController');
Route::post('/post/update/comment', ['as' => 'updateComment', 'uses' => 'CommentsController@postUpdateComment']);

app/Comments.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;

class Comments extends Model
{
    //
    protected $fillable = ['id', 'name', 'mail', 'age', 'title', 'comment'];
}

app/User.php
<?php

namespace App;

use Illuminate\Auth\Authenticatable;
use Illuminate\Database\Eloquent\Model;
use Illuminate\Auth\Passwords\CanResetPassword;
use Illuminate\Contracts\Auth\Authenticatable as AuthenticatableContract;
use Illuminate\Contracts\Auth\CanResetPassword as CanResetPasswordContract;

class User extends Model implements AuthenticatableContract, CanResetPasswordContract
{
    use Authenticatable, CanResetPassword;

    /**
     * The database table used by the model.
     *
     * @var string
     */
    protected $table = 'users';

    /**
     * The attributes that are mass assignable.
     *
     * @var array
     */
    protected $fillable = ['name', 'email', 'password'];

    /**
     * The attributes excluded from the model's JSON form.
     *
     * @var array
     */
    protected $hidden = ['password', 'remember_token'];
}

app/Http/Controllers/CommentsController.php
<?php

namespace App\Http\Controllers;

use Illuminate\Http\Request;

use App\Http\Requests;
use App\Http\Controllers\Controller;
use App\Comments;
use App\Http\Requests\CommentsRequest;
use App\Http\Requests\DataCommentRequest;

class CommentsController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return Response
     */
    public function index()
    {
        //
        $comments = [];
        if(Comments::all()->first()) {
            $comments = Comments::all()->first()->get();
        }

        return view('comments.list_comments', compact('comments'));    
        
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return Response
     */
    public function create()
    {
        //
        return view('comments.create');
    }

    /**
     * Store a newly created resource in storage.
     *
     * @return Response
     */
    public function store(Comments $comments, CommentsRequest $request)
    {
        //
        //dd($request->all());
        $comments->create($request->all());
        return redirect('comments')->with('message', 'It has created a new comment');

    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return Response
     */
    public function show($id)
    {
        //
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return Response
     */
    public function edit($id)
    {
        //
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  int  $id
     * @return Response
     */
    public function update($id)
    {
        //
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return Response
     */
    public function destroy($id)
    {
        //

        $comment = Comments::find($id);
        $comment->delete();
        return redirect('comments')->with('message', 'Comment destroyed');
    }

    /**
     *
     */
    public function postUpdateComment(DataCommentRequest $request)
    {
        $data = $request->all();
        $comment = Comments::find($data['pk']);
        $comment->$data['name'] = $data['value'];
        $comment->save();
        return response()->json('ok', 200);
    }
}

app/Http/Controllers/Controller.php
<?php

namespace App\Http\Controllers;

use Illuminate\Foundation\Bus\DispatchesJobs;
use Illuminate\Routing\Controller as BaseController;
use Illuminate\Foundation\Validation\ValidatesRequests;

abstract class Controller extends BaseController
{
    use DispatchesJobs, ValidatesRequests;
}

resources/views/comments/create.blade.php
@extends('layouts.app')

@section('content')
	<div id="wrapper-comments">
		<div class="title-comments"><span>Crear Comentarios</span></div>
		
		<div id="wrapper-form">
			<form id="form-create" method="post" action="{{ url('comments') }}">
				<input type="hidden" name="_token" value="{{ csrf_token() }}">
				<label>Nombre:</label><br/>
				<input type="text" id="name" name="name" placeholder="nombre"><br>
				<label>E-mail:</label><br/>
				<input type="email" id="mail" name="mail" placeholder="correo"><br>
				<label>Edad:</label><br/>
				<input type="text" id="age" name="age" placeholder="edad"><br>
				<label>Titulo:</label><br/>
				<input type="text" id="title" name="title" placeholder="title"><br>
				<label>Comentario:</label><br/>
				<textarea name="comment"></textarea><br/>
				<input type="submit" value="Enviar">
			</form>
		</div>
	</div>
@stop

resources/views/comments/index.blade.php
@extends('layouts.app')

@section('content')
	<div id="wrapper-comments">
		<div class="title-comments"><span>Menu de Comentarios</span></div>
		<div id="wrapper-options">
			<div class="menu-option"><span><a href="{{ route('comments.create') }}">Crear</a></span></div>
			<div class="menu-option"><span><a href="#">Actualizar</a></span></div>
			<div class="menu-option"><span><a href="#">Borrar</a></span></div>
			<div class="menu-option"><span><a href="#">Lista</a></span></div>
		</div>
	</div>
@stop

resources/views/comments/list_comments.blade.php
@extends('layouts.app')

@section('content')
    <div class="row">
        <div class="col-md-10 col-md-offset-1">
            <div class="row">
                <div class="col-xs-7 col-md-8"><h3>Listado de Comentarios</h3></div>
                <div class="col-xs-5 col-md-4">
                  <div class="row">
                    <div class="col-lg-12">
                        <div class="input-group">
                            <span class="input-group-btn">
                                <a href="{{ route('comments.create') }}" class="btn btn-success">Nuevo Comentario</a>
                            </span>
                        </div><!-- /input-group -->
                    </div><!-- /.col-lg-6 -->
                  </div><!-- /.row -->
                </div>
            </div>
                <table class="table table-hover">
                      @include('layouts._message')
                      <thead>
                        <tr>
                          <th>#</th>
                          <th>Nombre</th>
                          <th>E-mail</th>
                          <th>Edad</th>
                          <th>Titulo</th>
                          <th>Comentario</th>
                          <th>Creado</th>
                          <th>Actualizado</th>
                          <th>Acciones</th>
                        </tr>
                      </thead>
                      <tbody id="tbody-url" route="{!! route('updateComment') !!}">
                        @foreach ($comments as $comment)
                            
                            <tr>

                              <th scope="row">{{ $comment['id'] }}</th>
                              <td><a href="#" data-pk="{!! $comment['id'] !!}" class="x-name">{!! $comment['name'] !!}</a></td>
                              <td><a href="#" data-pk="{!! $comment['id'] !!}" class="x-mail">{!! $comment['mail'] !!}</a></td>
                              <td><a href="#" data-pk="{!! $comment['id'] !!}" class="x-age">{!! $comment['age'] !!}</a></td>
                              <td><a href="#" data-pk="{!! $comment['id'] !!}" class="x-title">{!! $comment['title'] !!}</a></td>
                              <td><a href="#" data-pk="{!! $comment['id'] !!}" class="x-comment">{!! $comment['comment'] !!}</a></td>
                              <td>{{ $comment['created_at'] }}</td>
                              <td>{{ $comment['updated_at'] }}</td>
                              <td><a href="#myModal" class="btn btn-danger modal-delete" data-toggle="modal" message="¿ Esta seguro que desea borrar el comentario: {{$comment['id']}} ?" route="{!! route('comments.destroy', ['id' => $comment['id'] ]) !!}" >Borrar Comentario</a></td>
                              <!--
                              <td>
                                {!! Form::open(['method' => 'DELETE', 'route' => ['comments.destroy', $comment['id']], 'role' => 'form',]) !!}
                                 <div class="btn-group">
                                  <input type="submit" value="Borrar Comentario" class="btn btn-danger">
                                </div>
                                {!! Form::close() !!}
                              </td> -->
                            </tr>
                        @endforeach
                      </tbody>
                      
                    </table>
                    
              </div>
            </div>
        </div>
    </div>
@endsection

resources/views/index.blade.php
@extends('layouts.app')

@section('content')
	<h1>Hola Mundo</h1>
@stop

resources/views/layouts/_message.blade.php
<!-- Aquí van los mensajes en caso de que existan -->
@if (Session::has('message'))
   <div class="alert alert-success {{ Session::has('message_important') ? 'alert-important' : '' }} ">
    @if(Session::has('message_important'))
      <button class='close' type='button' data-dismiss='alert' aria-hidden='true'>&times;</button>
    @endif
    {{ session('message') }}
   </div>
@endif

resources/views/layouts/_modal_message.blade.php
<div id="myModal" class="modal fade">
  <div class="modal-dialog">
    <div class="modal-content">
  
      <div class="modal-header" style="background-color:#d9534f;">
        <h4 class="modal-title" style="color:white;text-align:center;">Confirmation</h4>
      </div>
  
      <div class="modal-body">
        <h4 class="text-warning" id="message">(_message)</h4>
      </div>
      
      <div class="modal-footer">
        {!! Form::open(['method' => 'DELETE', 'class' => 'form-horizontal', 'url' => '', 'id' => 'form-modal-delete']) !!}
            {!! Form::submit('Accept', ['class' => 'btn btn-danger']) !!}
            <button type="button" class="btn btn-default" data-dismiss="modal">Cancel</button>
        {!! Form::close() !!}
      </div>
    </div>
  </div>
</div>

resources/views/layouts/_nav.blade.php
<nav class="navbar navbar-inverse ">
    <div class="container-fluid">
        <div class="navbar-header">
            <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1">
                <span class="sr-only">Toggle Navigation</span>
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
            </button>
            <a class="navbar-brand" href="#">System Ecce</a>
        </div>

        <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
            <ul class="nav navbar-nav">
                <li><a href="/">Home</a></li>
                @if (!Auth::guest())
                    <li><a href="{{ url('comments/') }}">Comentarios (abc)</a></li>
                @endif
            </ul>

            <ul class="nav navbar-nav navbar-right">
                @if (Auth::guest())
                    <li><a href="{{ url('/auth/login') }}">Login</a></li>
                    <li><a href="{{ url('/auth/register') }}">Register</a></li>
                @else
                    <li class="dropdown">
                        <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-expanded="false">{{ Auth::user()->name }} <span class="caret"></span></a>
                        <ul class="dropdown-menu" role="menu">
                            <li><a href="/auth/logout">Logout</a></li>
                        </ul>
                    </li>
                @endif
            </ul>
        </div>
    </div>
</nav>

resources/views/layouts/app.blade.php
<!DOCTYPE html>
<html lang="en">
<head>
	<meta charset="utf-8">
	<meta http-equiv="X-UA-Compatible" content="IE=edge">
  <meta name="csrf_token" content="{!! csrf_token() !!}">
  <meta content="authenticity_token" name="csrf-param" />
	<title>Ecce</title>
  <link href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.5/css/bootstrap.min.css" rel="stylesheet">
  <link href="//cdnjs.cloudflare.com/ajax/libs/x-editable/1.5.0/bootstrap3-editable/css/bootstrap-editable.css" rel="stylesheet"/>
  <link rel="stylesheet" type="text/css" href="{{ url('css/comments.css') }}">
</head>
<body>
  @include('layouts._nav')
  @include('layouts._modal_message')
  <div class="container-fluid">
    @yield('content')
  </div>
  <script src="//cdnjs.cloudflare.com/ajax/libs/jquery/2.1.3/jquery.min.js"></script>
  <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.5/js/bootstrap.min.js"></script>
  <script src="//cdnjs.cloudflare.com/ajax/libs/x-editable/1.5.0/bootstrap3-editable/js/bootstrap-editable.min.js"></script>
  <script src="{{ url('js/script.js') }}"></script>
  <script src="//cdn.ckeditor.com/4.4.7/full/ckeditor.js"></script>

  <script type="text/javascript">

    CKEDITOR.replace( 'comment',
        {
            //TODO: mover esta configuración a un archivo -> customConfig: 'js/ckeditor.js'
            language: 'en',
            toolbarGroups: [
                { name: 'clipboard',   groups: [ 'clipboard', 'undo' ] },
                { name: 'editing',     groups: [ 'find', 'selection', 'spellchecker' ] },
                { name: 'insert' },
                { name: 'basicstyles', groups: [ 'basicstyles', 'cleanup' ] },
                { name: 'paragraph',   groups: [ 'list', 'indent', 'blocks', 'align' ] },
                { name: 'styles' },
                { name: 'colors' }
            ]

        }
    );

</script>
</body>
</html>